/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_api_v2_core_address_pb = require('../../../../envoy/api/v2/core/address_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.exportSymbol('proto.envoy.service.auth.v2alpha.AttributeContext', null, global);
goog.exportSymbol('proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest', null, global);
goog.exportSymbol('proto.envoy.service.auth.v2alpha.AttributeContext.Peer', null, global);
goog.exportSymbol('proto.envoy.service.auth.v2alpha.AttributeContext.Request', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.service.auth.v2alpha.AttributeContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.service.auth.v2alpha.AttributeContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.service.auth.v2alpha.AttributeContext.displayName = 'proto.envoy.service.auth.v2alpha.AttributeContext';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.service.auth.v2alpha.AttributeContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v2alpha.AttributeContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    source: (f = msg.getSource()) && proto.envoy.service.auth.v2alpha.AttributeContext.Peer.toObject(includeInstance, f),
    destination: (f = msg.getDestination()) && proto.envoy.service.auth.v2alpha.AttributeContext.Peer.toObject(includeInstance, f),
    request: (f = msg.getRequest()) && proto.envoy.service.auth.v2alpha.AttributeContext.Request.toObject(includeInstance, f),
    contextExtensionsMap: (f = msg.getContextExtensionsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.service.auth.v2alpha.AttributeContext}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.service.auth.v2alpha.AttributeContext;
  return proto.envoy.service.auth.v2alpha.AttributeContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.service.auth.v2alpha.AttributeContext}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.service.auth.v2alpha.AttributeContext.Peer;
      reader.readMessage(value,proto.envoy.service.auth.v2alpha.AttributeContext.Peer.deserializeBinaryFromReader);
      msg.setSource(value);
      break;
    case 2:
      var value = new proto.envoy.service.auth.v2alpha.AttributeContext.Peer;
      reader.readMessage(value,proto.envoy.service.auth.v2alpha.AttributeContext.Peer.deserializeBinaryFromReader);
      msg.setDestination(value);
      break;
    case 4:
      var value = new proto.envoy.service.auth.v2alpha.AttributeContext.Request;
      reader.readMessage(value,proto.envoy.service.auth.v2alpha.AttributeContext.Request.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    case 10:
      var value = msg.getContextExtensionsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.service.auth.v2alpha.AttributeContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v2alpha.AttributeContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSource();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.envoy.service.auth.v2alpha.AttributeContext.Peer.serializeBinaryToWriter
    );
  }
  f = message.getDestination();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.service.auth.v2alpha.AttributeContext.Peer.serializeBinaryToWriter
    );
  }
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.envoy.service.auth.v2alpha.AttributeContext.Request.serializeBinaryToWriter
    );
  }
  f = message.getContextExtensionsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(10, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.service.auth.v2alpha.AttributeContext.Peer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.service.auth.v2alpha.AttributeContext.Peer.displayName = 'proto.envoy.service.auth.v2alpha.AttributeContext.Peer';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.service.auth.v2alpha.AttributeContext.Peer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext.Peer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: (f = msg.getAddress()) && envoy_api_v2_core_address_pb.Address.toObject(includeInstance, f),
    service: jspb.Message.getFieldWithDefault(msg, 2, ""),
    labelsMap: (f = msg.getLabelsMap()) ? f.toObject(includeInstance, undefined) : [],
    principal: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.service.auth.v2alpha.AttributeContext.Peer}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.service.auth.v2alpha.AttributeContext.Peer;
  return proto.envoy.service.auth.v2alpha.AttributeContext.Peer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext.Peer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.service.auth.v2alpha.AttributeContext.Peer}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_api_v2_core_address_pb.Address;
      reader.readMessage(value,envoy_api_v2_core_address_pb.Address.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setService(value);
      break;
    case 3:
      var value = msg.getLabelsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrincipal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.service.auth.v2alpha.AttributeContext.Peer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext.Peer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_api_v2_core_address_pb.Address.serializeBinaryToWriter
    );
  }
  f = message.getService();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLabelsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getPrincipal();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional envoy.api.v2.core.Address address = 1;
 * @return {?proto.envoy.api.v2.core.Address}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.getAddress = function() {
  return /** @type{?proto.envoy.api.v2.core.Address} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_address_pb.Address, 1));
};


/** @param {?proto.envoy.api.v2.core.Address|undefined} value */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.setAddress = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.clearAddress = function() {
  this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string service = 2;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.getService = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.setService = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * map<string, string> labels = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.getLabelsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.clearLabelsMap = function() {
  this.getLabelsMap().clear();
};


/**
 * optional string principal = 4;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.getPrincipal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.Peer.prototype.setPrincipal = function(value) {
  jspb.Message.setField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.service.auth.v2alpha.AttributeContext.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.service.auth.v2alpha.AttributeContext.Request.displayName = 'proto.envoy.service.auth.v2alpha.AttributeContext.Request';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.service.auth.v2alpha.AttributeContext.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext.Request} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
    time: (f = msg.getTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    http: (f = msg.getHttp()) && proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.service.auth.v2alpha.AttributeContext.Request}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.service.auth.v2alpha.AttributeContext.Request;
  return proto.envoy.service.auth.v2alpha.AttributeContext.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.service.auth.v2alpha.AttributeContext.Request}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTime(value);
      break;
    case 2:
      var value = new proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest;
      reader.readMessage(value,proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.deserializeBinaryFromReader);
      msg.setHttp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.service.auth.v2alpha.AttributeContext.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getHttp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp time = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.getTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.setTime = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.clearTime = function() {
  this.setTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.hasTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional HttpRequest http = 2;
 * @return {?proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.getHttp = function() {
  return /** @type{?proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest} */ (
    jspb.Message.getWrapperField(this, proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest, 2));
};


/** @param {?proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest|undefined} value */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.setHttp = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.clearHttp = function() {
  this.setHttp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.Request.prototype.hasHttp = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.displayName = 'proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    method: jspb.Message.getFieldWithDefault(msg, 2, ""),
    headersMap: (f = msg.getHeadersMap()) ? f.toObject(includeInstance, undefined) : [],
    path: jspb.Message.getFieldWithDefault(msg, 4, ""),
    host: jspb.Message.getFieldWithDefault(msg, 5, ""),
    scheme: jspb.Message.getFieldWithDefault(msg, 6, ""),
    query: jspb.Message.getFieldWithDefault(msg, 7, ""),
    fragment: jspb.Message.getFieldWithDefault(msg, 8, ""),
    size: jspb.Message.getFieldWithDefault(msg, 9, 0),
    protocol: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest;
  return proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMethod(value);
      break;
    case 3:
      var value = msg.getHeadersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHost(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setScheme(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuery(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setFragment(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSize(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setProtocol(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMethod();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHeadersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHost();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getScheme();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getQuery();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getFragment();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getProtocol();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string method = 2;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.setMethod = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * map<string, string> headers = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getHeadersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.clearHeadersMap = function() {
  this.getHeadersMap().clear();
};


/**
 * optional string path = 4;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.setPath = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string host = 5;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.setHost = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string scheme = 6;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getScheme = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.setScheme = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string query = 7;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getQuery = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.setQuery = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional string fragment = 8;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getFragment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.setFragment = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * optional int64 size = 9;
 * @return {number}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.setSize = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional string protocol = 10;
 * @return {string}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.getProtocol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.envoy.service.auth.v2alpha.AttributeContext.HttpRequest.prototype.setProtocol = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional Peer source = 1;
 * @return {?proto.envoy.service.auth.v2alpha.AttributeContext.Peer}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.getSource = function() {
  return /** @type{?proto.envoy.service.auth.v2alpha.AttributeContext.Peer} */ (
    jspb.Message.getWrapperField(this, proto.envoy.service.auth.v2alpha.AttributeContext.Peer, 1));
};


/** @param {?proto.envoy.service.auth.v2alpha.AttributeContext.Peer|undefined} value */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.setSource = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.envoy.service.auth.v2alpha.AttributeContext.prototype.clearSource = function() {
  this.setSource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.hasSource = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Peer destination = 2;
 * @return {?proto.envoy.service.auth.v2alpha.AttributeContext.Peer}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.getDestination = function() {
  return /** @type{?proto.envoy.service.auth.v2alpha.AttributeContext.Peer} */ (
    jspb.Message.getWrapperField(this, proto.envoy.service.auth.v2alpha.AttributeContext.Peer, 2));
};


/** @param {?proto.envoy.service.auth.v2alpha.AttributeContext.Peer|undefined} value */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.setDestination = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.envoy.service.auth.v2alpha.AttributeContext.prototype.clearDestination = function() {
  this.setDestination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.hasDestination = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Request request = 4;
 * @return {?proto.envoy.service.auth.v2alpha.AttributeContext.Request}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.getRequest = function() {
  return /** @type{?proto.envoy.service.auth.v2alpha.AttributeContext.Request} */ (
    jspb.Message.getWrapperField(this, proto.envoy.service.auth.v2alpha.AttributeContext.Request, 4));
};


/** @param {?proto.envoy.service.auth.v2alpha.AttributeContext.Request|undefined} value */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.setRequest = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.envoy.service.auth.v2alpha.AttributeContext.prototype.clearRequest = function() {
  this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * map<string, string> context_extensions = 10;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.envoy.service.auth.v2alpha.AttributeContext.prototype.getContextExtensionsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 10, opt_noLazyCreate,
      null));
};


proto.envoy.service.auth.v2alpha.AttributeContext.prototype.clearContextExtensionsMap = function() {
  this.getContextExtensionsMap().clear();
};


goog.object.extend(exports, proto.envoy.service.auth.v2alpha);
