/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var validate_validate_pb = require('../../../../validate/validate_pb.js');
var envoy_api_v2_core_address_pb = require('../../../../envoy/api/v2/core/address_pb.js');
var envoy_api_v2_route_route_pb = require('../../../../envoy/api/v2/route/route_pb.js');
var envoy_type_matcher_metadata_pb = require('../../../../envoy/type/matcher/metadata_pb.js');
var envoy_type_matcher_string_pb = require('../../../../envoy/type/matcher/string_pb.js');
goog.exportSymbol('proto.envoy.config.rbac.v2alpha.Permission', null, global);
goog.exportSymbol('proto.envoy.config.rbac.v2alpha.Permission.Set', null, global);
goog.exportSymbol('proto.envoy.config.rbac.v2alpha.Policy', null, global);
goog.exportSymbol('proto.envoy.config.rbac.v2alpha.Principal', null, global);
goog.exportSymbol('proto.envoy.config.rbac.v2alpha.Principal.Authenticated', null, global);
goog.exportSymbol('proto.envoy.config.rbac.v2alpha.Principal.Set', null, global);
goog.exportSymbol('proto.envoy.config.rbac.v2alpha.RBAC', null, global);
goog.exportSymbol('proto.envoy.config.rbac.v2alpha.RBAC.Action', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.rbac.v2alpha.RBAC = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.rbac.v2alpha.RBAC, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.config.rbac.v2alpha.RBAC.displayName = 'proto.envoy.config.rbac.v2alpha.RBAC';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.rbac.v2alpha.RBAC.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.rbac.v2alpha.RBAC.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.rbac.v2alpha.RBAC} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.RBAC.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, 0),
    policiesMap: (f = msg.getPoliciesMap()) ? f.toObject(includeInstance, proto.envoy.config.rbac.v2alpha.Policy.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.rbac.v2alpha.RBAC}
 */
proto.envoy.config.rbac.v2alpha.RBAC.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.rbac.v2alpha.RBAC;
  return proto.envoy.config.rbac.v2alpha.RBAC.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.rbac.v2alpha.RBAC} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.rbac.v2alpha.RBAC}
 */
proto.envoy.config.rbac.v2alpha.RBAC.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.envoy.config.rbac.v2alpha.RBAC.Action} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 2:
      var value = msg.getPoliciesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.envoy.config.rbac.v2alpha.Policy.deserializeBinaryFromReader);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.rbac.v2alpha.RBAC.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.rbac.v2alpha.RBAC.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.rbac.v2alpha.RBAC} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.RBAC.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getPoliciesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.envoy.config.rbac.v2alpha.Policy.serializeBinaryToWriter);
  }
};


/**
 * @enum {number}
 */
proto.envoy.config.rbac.v2alpha.RBAC.Action = {
  ALLOW: 0,
  DENY: 1
};

/**
 * optional Action action = 1;
 * @return {!proto.envoy.config.rbac.v2alpha.RBAC.Action}
 */
proto.envoy.config.rbac.v2alpha.RBAC.prototype.getAction = function() {
  return /** @type {!proto.envoy.config.rbac.v2alpha.RBAC.Action} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.envoy.config.rbac.v2alpha.RBAC.Action} value */
proto.envoy.config.rbac.v2alpha.RBAC.prototype.setAction = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * map<string, Policy> policies = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.envoy.config.rbac.v2alpha.Policy>}
 */
proto.envoy.config.rbac.v2alpha.RBAC.prototype.getPoliciesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.envoy.config.rbac.v2alpha.Policy>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.envoy.config.rbac.v2alpha.Policy));
};


proto.envoy.config.rbac.v2alpha.RBAC.prototype.clearPoliciesMap = function() {
  this.getPoliciesMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.rbac.v2alpha.Policy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.rbac.v2alpha.Policy.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.rbac.v2alpha.Policy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.config.rbac.v2alpha.Policy.displayName = 'proto.envoy.config.rbac.v2alpha.Policy';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.rbac.v2alpha.Policy.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.rbac.v2alpha.Policy.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.rbac.v2alpha.Policy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.rbac.v2alpha.Policy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Policy.toObject = function(includeInstance, msg) {
  var f, obj = {
    permissionsList: jspb.Message.toObjectList(msg.getPermissionsList(),
    proto.envoy.config.rbac.v2alpha.Permission.toObject, includeInstance),
    principalsList: jspb.Message.toObjectList(msg.getPrincipalsList(),
    proto.envoy.config.rbac.v2alpha.Principal.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.rbac.v2alpha.Policy}
 */
proto.envoy.config.rbac.v2alpha.Policy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.rbac.v2alpha.Policy;
  return proto.envoy.config.rbac.v2alpha.Policy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.rbac.v2alpha.Policy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.rbac.v2alpha.Policy}
 */
proto.envoy.config.rbac.v2alpha.Policy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.config.rbac.v2alpha.Permission;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Permission.deserializeBinaryFromReader);
      msg.addPermissions(value);
      break;
    case 2:
      var value = new proto.envoy.config.rbac.v2alpha.Principal;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Principal.deserializeBinaryFromReader);
      msg.addPrincipals(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.rbac.v2alpha.Policy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.rbac.v2alpha.Policy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.rbac.v2alpha.Policy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Policy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPermissionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.envoy.config.rbac.v2alpha.Permission.serializeBinaryToWriter
    );
  }
  f = message.getPrincipalsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.envoy.config.rbac.v2alpha.Principal.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Permission permissions = 1;
 * @return {!Array.<!proto.envoy.config.rbac.v2alpha.Permission>}
 */
proto.envoy.config.rbac.v2alpha.Policy.prototype.getPermissionsList = function() {
  return /** @type{!Array.<!proto.envoy.config.rbac.v2alpha.Permission>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.rbac.v2alpha.Permission, 1));
};


/** @param {!Array.<!proto.envoy.config.rbac.v2alpha.Permission>} value */
proto.envoy.config.rbac.v2alpha.Policy.prototype.setPermissionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.envoy.config.rbac.v2alpha.Permission=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.rbac.v2alpha.Permission}
 */
proto.envoy.config.rbac.v2alpha.Policy.prototype.addPermissions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.envoy.config.rbac.v2alpha.Permission, opt_index);
};


proto.envoy.config.rbac.v2alpha.Policy.prototype.clearPermissionsList = function() {
  this.setPermissionsList([]);
};


/**
 * repeated Principal principals = 2;
 * @return {!Array.<!proto.envoy.config.rbac.v2alpha.Principal>}
 */
proto.envoy.config.rbac.v2alpha.Policy.prototype.getPrincipalsList = function() {
  return /** @type{!Array.<!proto.envoy.config.rbac.v2alpha.Principal>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.rbac.v2alpha.Principal, 2));
};


/** @param {!Array.<!proto.envoy.config.rbac.v2alpha.Principal>} value */
proto.envoy.config.rbac.v2alpha.Policy.prototype.setPrincipalsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.envoy.config.rbac.v2alpha.Principal=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.rbac.v2alpha.Principal}
 */
proto.envoy.config.rbac.v2alpha.Policy.prototype.addPrincipals = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.envoy.config.rbac.v2alpha.Principal, opt_index);
};


proto.envoy.config.rbac.v2alpha.Policy.prototype.clearPrincipalsList = function() {
  this.setPrincipalsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.rbac.v2alpha.Permission = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_);
};
goog.inherits(proto.envoy.config.rbac.v2alpha.Permission, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.config.rbac.v2alpha.Permission.displayName = 'proto.envoy.config.rbac.v2alpha.Permission';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_ = [[1,2,3,4,5,6,7,8,9]];

/**
 * @enum {number}
 */
proto.envoy.config.rbac.v2alpha.Permission.RuleCase = {
  RULE_NOT_SET: 0,
  AND_RULES: 1,
  OR_RULES: 2,
  ANY: 3,
  HEADER: 4,
  DESTINATION_IP: 5,
  DESTINATION_PORT: 6,
  METADATA: 7,
  NOT_RULE: 8,
  REQUESTED_SERVER_NAME: 9
};

/**
 * @return {proto.envoy.config.rbac.v2alpha.Permission.RuleCase}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getRuleCase = function() {
  return /** @type {proto.envoy.config.rbac.v2alpha.Permission.RuleCase} */(jspb.Message.computeOneofCase(this, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.rbac.v2alpha.Permission.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.rbac.v2alpha.Permission} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Permission.toObject = function(includeInstance, msg) {
  var f, obj = {
    andRules: (f = msg.getAndRules()) && proto.envoy.config.rbac.v2alpha.Permission.Set.toObject(includeInstance, f),
    orRules: (f = msg.getOrRules()) && proto.envoy.config.rbac.v2alpha.Permission.Set.toObject(includeInstance, f),
    any: jspb.Message.getFieldWithDefault(msg, 3, false),
    header: (f = msg.getHeader()) && envoy_api_v2_route_route_pb.HeaderMatcher.toObject(includeInstance, f),
    destinationIp: (f = msg.getDestinationIp()) && envoy_api_v2_core_address_pb.CidrRange.toObject(includeInstance, f),
    destinationPort: jspb.Message.getFieldWithDefault(msg, 6, 0),
    metadata: (f = msg.getMetadata()) && envoy_type_matcher_metadata_pb.MetadataMatcher.toObject(includeInstance, f),
    notRule: (f = msg.getNotRule()) && proto.envoy.config.rbac.v2alpha.Permission.toObject(includeInstance, f),
    requestedServerName: (f = msg.getRequestedServerName()) && envoy_type_matcher_string_pb.StringMatcher.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.rbac.v2alpha.Permission}
 */
proto.envoy.config.rbac.v2alpha.Permission.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.rbac.v2alpha.Permission;
  return proto.envoy.config.rbac.v2alpha.Permission.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.rbac.v2alpha.Permission} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.rbac.v2alpha.Permission}
 */
proto.envoy.config.rbac.v2alpha.Permission.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.config.rbac.v2alpha.Permission.Set;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Permission.Set.deserializeBinaryFromReader);
      msg.setAndRules(value);
      break;
    case 2:
      var value = new proto.envoy.config.rbac.v2alpha.Permission.Set;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Permission.Set.deserializeBinaryFromReader);
      msg.setOrRules(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAny(value);
      break;
    case 4:
      var value = new envoy_api_v2_route_route_pb.HeaderMatcher;
      reader.readMessage(value,envoy_api_v2_route_route_pb.HeaderMatcher.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 5:
      var value = new envoy_api_v2_core_address_pb.CidrRange;
      reader.readMessage(value,envoy_api_v2_core_address_pb.CidrRange.deserializeBinaryFromReader);
      msg.setDestinationIp(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDestinationPort(value);
      break;
    case 7:
      var value = new envoy_type_matcher_metadata_pb.MetadataMatcher;
      reader.readMessage(value,envoy_type_matcher_metadata_pb.MetadataMatcher.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 8:
      var value = new proto.envoy.config.rbac.v2alpha.Permission;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Permission.deserializeBinaryFromReader);
      msg.setNotRule(value);
      break;
    case 9:
      var value = new envoy_type_matcher_string_pb.StringMatcher;
      reader.readMessage(value,envoy_type_matcher_string_pb.StringMatcher.deserializeBinaryFromReader);
      msg.setRequestedServerName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.rbac.v2alpha.Permission.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.rbac.v2alpha.Permission} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Permission.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAndRules();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.envoy.config.rbac.v2alpha.Permission.Set.serializeBinaryToWriter
    );
  }
  f = message.getOrRules();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.config.rbac.v2alpha.Permission.Set.serializeBinaryToWriter
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      envoy_api_v2_route_route_pb.HeaderMatcher.serializeBinaryToWriter
    );
  }
  f = message.getDestinationIp();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      envoy_api_v2_core_address_pb.CidrRange.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      envoy_type_matcher_metadata_pb.MetadataMatcher.serializeBinaryToWriter
    );
  }
  f = message.getNotRule();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.envoy.config.rbac.v2alpha.Permission.serializeBinaryToWriter
    );
  }
  f = message.getRequestedServerName();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      envoy_type_matcher_string_pb.StringMatcher.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.rbac.v2alpha.Permission.Set = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.rbac.v2alpha.Permission.Set.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.rbac.v2alpha.Permission.Set, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.config.rbac.v2alpha.Permission.Set.displayName = 'proto.envoy.config.rbac.v2alpha.Permission.Set';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.rbac.v2alpha.Permission.Set.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.rbac.v2alpha.Permission.Set.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.rbac.v2alpha.Permission.Set.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.rbac.v2alpha.Permission.Set} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Permission.Set.toObject = function(includeInstance, msg) {
  var f, obj = {
    rulesList: jspb.Message.toObjectList(msg.getRulesList(),
    proto.envoy.config.rbac.v2alpha.Permission.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.rbac.v2alpha.Permission.Set}
 */
proto.envoy.config.rbac.v2alpha.Permission.Set.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.rbac.v2alpha.Permission.Set;
  return proto.envoy.config.rbac.v2alpha.Permission.Set.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.rbac.v2alpha.Permission.Set} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.rbac.v2alpha.Permission.Set}
 */
proto.envoy.config.rbac.v2alpha.Permission.Set.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.config.rbac.v2alpha.Permission;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Permission.deserializeBinaryFromReader);
      msg.addRules(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.rbac.v2alpha.Permission.Set.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.rbac.v2alpha.Permission.Set.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.rbac.v2alpha.Permission.Set} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Permission.Set.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRulesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.envoy.config.rbac.v2alpha.Permission.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Permission rules = 1;
 * @return {!Array.<!proto.envoy.config.rbac.v2alpha.Permission>}
 */
proto.envoy.config.rbac.v2alpha.Permission.Set.prototype.getRulesList = function() {
  return /** @type{!Array.<!proto.envoy.config.rbac.v2alpha.Permission>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.rbac.v2alpha.Permission, 1));
};


/** @param {!Array.<!proto.envoy.config.rbac.v2alpha.Permission>} value */
proto.envoy.config.rbac.v2alpha.Permission.Set.prototype.setRulesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.envoy.config.rbac.v2alpha.Permission=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.rbac.v2alpha.Permission}
 */
proto.envoy.config.rbac.v2alpha.Permission.Set.prototype.addRules = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.envoy.config.rbac.v2alpha.Permission, opt_index);
};


proto.envoy.config.rbac.v2alpha.Permission.Set.prototype.clearRulesList = function() {
  this.setRulesList([]);
};


/**
 * optional Set and_rules = 1;
 * @return {?proto.envoy.config.rbac.v2alpha.Permission.Set}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getAndRules = function() {
  return /** @type{?proto.envoy.config.rbac.v2alpha.Permission.Set} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.rbac.v2alpha.Permission.Set, 1));
};


/** @param {?proto.envoy.config.rbac.v2alpha.Permission.Set|undefined} value */
proto.envoy.config.rbac.v2alpha.Permission.prototype.setAndRules = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Permission.prototype.clearAndRules = function() {
  this.setAndRules(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.hasAndRules = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Set or_rules = 2;
 * @return {?proto.envoy.config.rbac.v2alpha.Permission.Set}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getOrRules = function() {
  return /** @type{?proto.envoy.config.rbac.v2alpha.Permission.Set} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.rbac.v2alpha.Permission.Set, 2));
};


/** @param {?proto.envoy.config.rbac.v2alpha.Permission.Set|undefined} value */
proto.envoy.config.rbac.v2alpha.Permission.prototype.setOrRules = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Permission.prototype.clearOrRules = function() {
  this.setOrRules(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.hasOrRules = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool any = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getAny = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.envoy.config.rbac.v2alpha.Permission.prototype.setAny = function(value) {
  jspb.Message.setOneofField(this, 3, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Permission.prototype.clearAny = function() {
  jspb.Message.setOneofField(this, 3, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.hasAny = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional envoy.api.v2.route.HeaderMatcher header = 4;
 * @return {?proto.envoy.api.v2.route.HeaderMatcher}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getHeader = function() {
  return /** @type{?proto.envoy.api.v2.route.HeaderMatcher} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_route_route_pb.HeaderMatcher, 4));
};


/** @param {?proto.envoy.api.v2.route.HeaderMatcher|undefined} value */
proto.envoy.config.rbac.v2alpha.Permission.prototype.setHeader = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Permission.prototype.clearHeader = function() {
  this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional envoy.api.v2.core.CidrRange destination_ip = 5;
 * @return {?proto.envoy.api.v2.core.CidrRange}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getDestinationIp = function() {
  return /** @type{?proto.envoy.api.v2.core.CidrRange} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_address_pb.CidrRange, 5));
};


/** @param {?proto.envoy.api.v2.core.CidrRange|undefined} value */
proto.envoy.config.rbac.v2alpha.Permission.prototype.setDestinationIp = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Permission.prototype.clearDestinationIp = function() {
  this.setDestinationIp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.hasDestinationIp = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional uint32 destination_port = 6;
 * @return {number}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getDestinationPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.envoy.config.rbac.v2alpha.Permission.prototype.setDestinationPort = function(value) {
  jspb.Message.setOneofField(this, 6, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Permission.prototype.clearDestinationPort = function() {
  jspb.Message.setOneofField(this, 6, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.hasDestinationPort = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional envoy.type.matcher.MetadataMatcher metadata = 7;
 * @return {?proto.envoy.type.matcher.MetadataMatcher}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getMetadata = function() {
  return /** @type{?proto.envoy.type.matcher.MetadataMatcher} */ (
    jspb.Message.getWrapperField(this, envoy_type_matcher_metadata_pb.MetadataMatcher, 7));
};


/** @param {?proto.envoy.type.matcher.MetadataMatcher|undefined} value */
proto.envoy.config.rbac.v2alpha.Permission.prototype.setMetadata = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Permission.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Permission not_rule = 8;
 * @return {?proto.envoy.config.rbac.v2alpha.Permission}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getNotRule = function() {
  return /** @type{?proto.envoy.config.rbac.v2alpha.Permission} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.rbac.v2alpha.Permission, 8));
};


/** @param {?proto.envoy.config.rbac.v2alpha.Permission|undefined} value */
proto.envoy.config.rbac.v2alpha.Permission.prototype.setNotRule = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Permission.prototype.clearNotRule = function() {
  this.setNotRule(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.hasNotRule = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional envoy.type.matcher.StringMatcher requested_server_name = 9;
 * @return {?proto.envoy.type.matcher.StringMatcher}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.getRequestedServerName = function() {
  return /** @type{?proto.envoy.type.matcher.StringMatcher} */ (
    jspb.Message.getWrapperField(this, envoy_type_matcher_string_pb.StringMatcher, 9));
};


/** @param {?proto.envoy.type.matcher.StringMatcher|undefined} value */
proto.envoy.config.rbac.v2alpha.Permission.prototype.setRequestedServerName = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.envoy.config.rbac.v2alpha.Permission.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Permission.prototype.clearRequestedServerName = function() {
  this.setRequestedServerName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Permission.prototype.hasRequestedServerName = function() {
  return jspb.Message.getField(this, 9) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.rbac.v2alpha.Principal = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_);
};
goog.inherits(proto.envoy.config.rbac.v2alpha.Principal, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.config.rbac.v2alpha.Principal.displayName = 'proto.envoy.config.rbac.v2alpha.Principal';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_ = [[1,2,3,4,5,6,7,8]];

/**
 * @enum {number}
 */
proto.envoy.config.rbac.v2alpha.Principal.IdentifierCase = {
  IDENTIFIER_NOT_SET: 0,
  AND_IDS: 1,
  OR_IDS: 2,
  ANY: 3,
  AUTHENTICATED: 4,
  SOURCE_IP: 5,
  HEADER: 6,
  METADATA: 7,
  NOT_ID: 8
};

/**
 * @return {proto.envoy.config.rbac.v2alpha.Principal.IdentifierCase}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.getIdentifierCase = function() {
  return /** @type {proto.envoy.config.rbac.v2alpha.Principal.IdentifierCase} */(jspb.Message.computeOneofCase(this, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.rbac.v2alpha.Principal.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.rbac.v2alpha.Principal} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Principal.toObject = function(includeInstance, msg) {
  var f, obj = {
    andIds: (f = msg.getAndIds()) && proto.envoy.config.rbac.v2alpha.Principal.Set.toObject(includeInstance, f),
    orIds: (f = msg.getOrIds()) && proto.envoy.config.rbac.v2alpha.Principal.Set.toObject(includeInstance, f),
    any: jspb.Message.getFieldWithDefault(msg, 3, false),
    authenticated: (f = msg.getAuthenticated()) && proto.envoy.config.rbac.v2alpha.Principal.Authenticated.toObject(includeInstance, f),
    sourceIp: (f = msg.getSourceIp()) && envoy_api_v2_core_address_pb.CidrRange.toObject(includeInstance, f),
    header: (f = msg.getHeader()) && envoy_api_v2_route_route_pb.HeaderMatcher.toObject(includeInstance, f),
    metadata: (f = msg.getMetadata()) && envoy_type_matcher_metadata_pb.MetadataMatcher.toObject(includeInstance, f),
    notId: (f = msg.getNotId()) && proto.envoy.config.rbac.v2alpha.Principal.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.rbac.v2alpha.Principal}
 */
proto.envoy.config.rbac.v2alpha.Principal.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.rbac.v2alpha.Principal;
  return proto.envoy.config.rbac.v2alpha.Principal.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.rbac.v2alpha.Principal} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.rbac.v2alpha.Principal}
 */
proto.envoy.config.rbac.v2alpha.Principal.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.config.rbac.v2alpha.Principal.Set;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Principal.Set.deserializeBinaryFromReader);
      msg.setAndIds(value);
      break;
    case 2:
      var value = new proto.envoy.config.rbac.v2alpha.Principal.Set;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Principal.Set.deserializeBinaryFromReader);
      msg.setOrIds(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAny(value);
      break;
    case 4:
      var value = new proto.envoy.config.rbac.v2alpha.Principal.Authenticated;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Principal.Authenticated.deserializeBinaryFromReader);
      msg.setAuthenticated(value);
      break;
    case 5:
      var value = new envoy_api_v2_core_address_pb.CidrRange;
      reader.readMessage(value,envoy_api_v2_core_address_pb.CidrRange.deserializeBinaryFromReader);
      msg.setSourceIp(value);
      break;
    case 6:
      var value = new envoy_api_v2_route_route_pb.HeaderMatcher;
      reader.readMessage(value,envoy_api_v2_route_route_pb.HeaderMatcher.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 7:
      var value = new envoy_type_matcher_metadata_pb.MetadataMatcher;
      reader.readMessage(value,envoy_type_matcher_metadata_pb.MetadataMatcher.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 8:
      var value = new proto.envoy.config.rbac.v2alpha.Principal;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Principal.deserializeBinaryFromReader);
      msg.setNotId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.rbac.v2alpha.Principal.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.rbac.v2alpha.Principal} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Principal.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAndIds();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.envoy.config.rbac.v2alpha.Principal.Set.serializeBinaryToWriter
    );
  }
  f = message.getOrIds();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.config.rbac.v2alpha.Principal.Set.serializeBinaryToWriter
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getAuthenticated();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.envoy.config.rbac.v2alpha.Principal.Authenticated.serializeBinaryToWriter
    );
  }
  f = message.getSourceIp();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      envoy_api_v2_core_address_pb.CidrRange.serializeBinaryToWriter
    );
  }
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      envoy_api_v2_route_route_pb.HeaderMatcher.serializeBinaryToWriter
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      envoy_type_matcher_metadata_pb.MetadataMatcher.serializeBinaryToWriter
    );
  }
  f = message.getNotId();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.envoy.config.rbac.v2alpha.Principal.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.rbac.v2alpha.Principal.Set = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.config.rbac.v2alpha.Principal.Set.repeatedFields_, null);
};
goog.inherits(proto.envoy.config.rbac.v2alpha.Principal.Set, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.config.rbac.v2alpha.Principal.Set.displayName = 'proto.envoy.config.rbac.v2alpha.Principal.Set';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.config.rbac.v2alpha.Principal.Set.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.rbac.v2alpha.Principal.Set.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.rbac.v2alpha.Principal.Set.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.rbac.v2alpha.Principal.Set} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Principal.Set.toObject = function(includeInstance, msg) {
  var f, obj = {
    idsList: jspb.Message.toObjectList(msg.getIdsList(),
    proto.envoy.config.rbac.v2alpha.Principal.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.rbac.v2alpha.Principal.Set}
 */
proto.envoy.config.rbac.v2alpha.Principal.Set.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.rbac.v2alpha.Principal.Set;
  return proto.envoy.config.rbac.v2alpha.Principal.Set.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.rbac.v2alpha.Principal.Set} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.rbac.v2alpha.Principal.Set}
 */
proto.envoy.config.rbac.v2alpha.Principal.Set.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.config.rbac.v2alpha.Principal;
      reader.readMessage(value,proto.envoy.config.rbac.v2alpha.Principal.deserializeBinaryFromReader);
      msg.addIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.rbac.v2alpha.Principal.Set.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.rbac.v2alpha.Principal.Set.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.rbac.v2alpha.Principal.Set} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Principal.Set.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.envoy.config.rbac.v2alpha.Principal.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Principal ids = 1;
 * @return {!Array.<!proto.envoy.config.rbac.v2alpha.Principal>}
 */
proto.envoy.config.rbac.v2alpha.Principal.Set.prototype.getIdsList = function() {
  return /** @type{!Array.<!proto.envoy.config.rbac.v2alpha.Principal>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.config.rbac.v2alpha.Principal, 1));
};


/** @param {!Array.<!proto.envoy.config.rbac.v2alpha.Principal>} value */
proto.envoy.config.rbac.v2alpha.Principal.Set.prototype.setIdsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.envoy.config.rbac.v2alpha.Principal=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.rbac.v2alpha.Principal}
 */
proto.envoy.config.rbac.v2alpha.Principal.Set.prototype.addIds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.envoy.config.rbac.v2alpha.Principal, opt_index);
};


proto.envoy.config.rbac.v2alpha.Principal.Set.prototype.clearIdsList = function() {
  this.setIdsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.rbac.v2alpha.Principal.Authenticated, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.config.rbac.v2alpha.Principal.Authenticated.displayName = 'proto.envoy.config.rbac.v2alpha.Principal.Authenticated';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.rbac.v2alpha.Principal.Authenticated.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.rbac.v2alpha.Principal.Authenticated} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated.toObject = function(includeInstance, msg) {
  var f, obj = {
    principalName: (f = msg.getPrincipalName()) && envoy_type_matcher_string_pb.StringMatcher.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.rbac.v2alpha.Principal.Authenticated}
 */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.rbac.v2alpha.Principal.Authenticated;
  return proto.envoy.config.rbac.v2alpha.Principal.Authenticated.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.rbac.v2alpha.Principal.Authenticated} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.rbac.v2alpha.Principal.Authenticated}
 */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new envoy_type_matcher_string_pb.StringMatcher;
      reader.readMessage(value,envoy_type_matcher_string_pb.StringMatcher.deserializeBinaryFromReader);
      msg.setPrincipalName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.rbac.v2alpha.Principal.Authenticated.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.rbac.v2alpha.Principal.Authenticated} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrincipalName();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      envoy_type_matcher_string_pb.StringMatcher.serializeBinaryToWriter
    );
  }
};


/**
 * optional envoy.type.matcher.StringMatcher principal_name = 2;
 * @return {?proto.envoy.type.matcher.StringMatcher}
 */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated.prototype.getPrincipalName = function() {
  return /** @type{?proto.envoy.type.matcher.StringMatcher} */ (
    jspb.Message.getWrapperField(this, envoy_type_matcher_string_pb.StringMatcher, 2));
};


/** @param {?proto.envoy.type.matcher.StringMatcher|undefined} value */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated.prototype.setPrincipalName = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.envoy.config.rbac.v2alpha.Principal.Authenticated.prototype.clearPrincipalName = function() {
  this.setPrincipalName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.Authenticated.prototype.hasPrincipalName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Set and_ids = 1;
 * @return {?proto.envoy.config.rbac.v2alpha.Principal.Set}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.getAndIds = function() {
  return /** @type{?proto.envoy.config.rbac.v2alpha.Principal.Set} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.rbac.v2alpha.Principal.Set, 1));
};


/** @param {?proto.envoy.config.rbac.v2alpha.Principal.Set|undefined} value */
proto.envoy.config.rbac.v2alpha.Principal.prototype.setAndIds = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Principal.prototype.clearAndIds = function() {
  this.setAndIds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.hasAndIds = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Set or_ids = 2;
 * @return {?proto.envoy.config.rbac.v2alpha.Principal.Set}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.getOrIds = function() {
  return /** @type{?proto.envoy.config.rbac.v2alpha.Principal.Set} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.rbac.v2alpha.Principal.Set, 2));
};


/** @param {?proto.envoy.config.rbac.v2alpha.Principal.Set|undefined} value */
proto.envoy.config.rbac.v2alpha.Principal.prototype.setOrIds = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Principal.prototype.clearOrIds = function() {
  this.setOrIds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.hasOrIds = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool any = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.getAny = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.envoy.config.rbac.v2alpha.Principal.prototype.setAny = function(value) {
  jspb.Message.setOneofField(this, 3, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Principal.prototype.clearAny = function() {
  jspb.Message.setOneofField(this, 3, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.hasAny = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Authenticated authenticated = 4;
 * @return {?proto.envoy.config.rbac.v2alpha.Principal.Authenticated}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.getAuthenticated = function() {
  return /** @type{?proto.envoy.config.rbac.v2alpha.Principal.Authenticated} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.rbac.v2alpha.Principal.Authenticated, 4));
};


/** @param {?proto.envoy.config.rbac.v2alpha.Principal.Authenticated|undefined} value */
proto.envoy.config.rbac.v2alpha.Principal.prototype.setAuthenticated = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Principal.prototype.clearAuthenticated = function() {
  this.setAuthenticated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.hasAuthenticated = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional envoy.api.v2.core.CidrRange source_ip = 5;
 * @return {?proto.envoy.api.v2.core.CidrRange}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.getSourceIp = function() {
  return /** @type{?proto.envoy.api.v2.core.CidrRange} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_address_pb.CidrRange, 5));
};


/** @param {?proto.envoy.api.v2.core.CidrRange|undefined} value */
proto.envoy.config.rbac.v2alpha.Principal.prototype.setSourceIp = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Principal.prototype.clearSourceIp = function() {
  this.setSourceIp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.hasSourceIp = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional envoy.api.v2.route.HeaderMatcher header = 6;
 * @return {?proto.envoy.api.v2.route.HeaderMatcher}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.getHeader = function() {
  return /** @type{?proto.envoy.api.v2.route.HeaderMatcher} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_route_route_pb.HeaderMatcher, 6));
};


/** @param {?proto.envoy.api.v2.route.HeaderMatcher|undefined} value */
proto.envoy.config.rbac.v2alpha.Principal.prototype.setHeader = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Principal.prototype.clearHeader = function() {
  this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional envoy.type.matcher.MetadataMatcher metadata = 7;
 * @return {?proto.envoy.type.matcher.MetadataMatcher}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.getMetadata = function() {
  return /** @type{?proto.envoy.type.matcher.MetadataMatcher} */ (
    jspb.Message.getWrapperField(this, envoy_type_matcher_metadata_pb.MetadataMatcher, 7));
};


/** @param {?proto.envoy.type.matcher.MetadataMatcher|undefined} value */
proto.envoy.config.rbac.v2alpha.Principal.prototype.setMetadata = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Principal.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Principal not_id = 8;
 * @return {?proto.envoy.config.rbac.v2alpha.Principal}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.getNotId = function() {
  return /** @type{?proto.envoy.config.rbac.v2alpha.Principal} */ (
    jspb.Message.getWrapperField(this, proto.envoy.config.rbac.v2alpha.Principal, 8));
};


/** @param {?proto.envoy.config.rbac.v2alpha.Principal|undefined} value */
proto.envoy.config.rbac.v2alpha.Principal.prototype.setNotId = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.envoy.config.rbac.v2alpha.Principal.oneofGroups_[0], value);
};


proto.envoy.config.rbac.v2alpha.Principal.prototype.clearNotId = function() {
  this.setNotId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.rbac.v2alpha.Principal.prototype.hasNotId = function() {
  return jspb.Message.getField(this, 8) != null;
};


goog.object.extend(exports, proto.envoy.config.rbac.v2alpha);
