/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_api_v2_core_address_pb = require('../../../../envoy/api/v2/core/address_pb.js');
var envoy_api_v2_core_base_pb = require('../../../../envoy/api/v2/core/base_pb.js');
var envoy_api_v2_core_health_check_pb = require('../../../../envoy/api/v2/core/health_check_pb.js');
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
var validate_validate_pb = require('../../../../validate/validate_pb.js');
var gogoproto_gogo_pb = require('../../../../gogoproto/gogo_pb.js');
goog.exportSymbol('proto.envoy.api.v2.endpoint.Endpoint', null, global);
goog.exportSymbol('proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig', null, global);
goog.exportSymbol('proto.envoy.api.v2.endpoint.LbEndpoint', null, global);
goog.exportSymbol('proto.envoy.api.v2.endpoint.LocalityLbEndpoints', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.endpoint.Endpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.api.v2.endpoint.Endpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.api.v2.endpoint.Endpoint.displayName = 'proto.envoy.api.v2.endpoint.Endpoint';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.endpoint.Endpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.endpoint.Endpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.endpoint.Endpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.endpoint.Endpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: (f = msg.getAddress()) && envoy_api_v2_core_address_pb.Address.toObject(includeInstance, f),
    healthCheckConfig: (f = msg.getHealthCheckConfig()) && proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.endpoint.Endpoint}
 */
proto.envoy.api.v2.endpoint.Endpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.endpoint.Endpoint;
  return proto.envoy.api.v2.endpoint.Endpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.endpoint.Endpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.endpoint.Endpoint}
 */
proto.envoy.api.v2.endpoint.Endpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_api_v2_core_address_pb.Address;
      reader.readMessage(value,envoy_api_v2_core_address_pb.Address.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    case 2:
      var value = new proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig;
      reader.readMessage(value,proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.deserializeBinaryFromReader);
      msg.setHealthCheckConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.endpoint.Endpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.endpoint.Endpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.endpoint.Endpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.endpoint.Endpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_api_v2_core_address_pb.Address.serializeBinaryToWriter
    );
  }
  f = message.getHealthCheckConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.displayName = 'proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    portValue: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig}
 */
proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig;
  return proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig}
 */
proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPortValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPortValue();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
};


/**
 * optional uint32 port_value = 1;
 * @return {number}
 */
proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.prototype.getPortValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig.prototype.setPortValue = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional envoy.api.v2.core.Address address = 1;
 * @return {?proto.envoy.api.v2.core.Address}
 */
proto.envoy.api.v2.endpoint.Endpoint.prototype.getAddress = function() {
  return /** @type{?proto.envoy.api.v2.core.Address} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_address_pb.Address, 1));
};


/** @param {?proto.envoy.api.v2.core.Address|undefined} value */
proto.envoy.api.v2.endpoint.Endpoint.prototype.setAddress = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.envoy.api.v2.endpoint.Endpoint.prototype.clearAddress = function() {
  this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.api.v2.endpoint.Endpoint.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional HealthCheckConfig health_check_config = 2;
 * @return {?proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig}
 */
proto.envoy.api.v2.endpoint.Endpoint.prototype.getHealthCheckConfig = function() {
  return /** @type{?proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig} */ (
    jspb.Message.getWrapperField(this, proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig, 2));
};


/** @param {?proto.envoy.api.v2.endpoint.Endpoint.HealthCheckConfig|undefined} value */
proto.envoy.api.v2.endpoint.Endpoint.prototype.setHealthCheckConfig = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.envoy.api.v2.endpoint.Endpoint.prototype.clearHealthCheckConfig = function() {
  this.setHealthCheckConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.api.v2.endpoint.Endpoint.prototype.hasHealthCheckConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.endpoint.LbEndpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.api.v2.endpoint.LbEndpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.api.v2.endpoint.LbEndpoint.displayName = 'proto.envoy.api.v2.endpoint.LbEndpoint';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.endpoint.LbEndpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.endpoint.LbEndpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.endpoint.LbEndpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    endpoint: (f = msg.getEndpoint()) && proto.envoy.api.v2.endpoint.Endpoint.toObject(includeInstance, f),
    healthStatus: jspb.Message.getFieldWithDefault(msg, 2, 0),
    metadata: (f = msg.getMetadata()) && envoy_api_v2_core_base_pb.Metadata.toObject(includeInstance, f),
    loadBalancingWeight: (f = msg.getLoadBalancingWeight()) && google_protobuf_wrappers_pb.UInt32Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.endpoint.LbEndpoint}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.endpoint.LbEndpoint;
  return proto.envoy.api.v2.endpoint.LbEndpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.endpoint.LbEndpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.endpoint.LbEndpoint}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.api.v2.endpoint.Endpoint;
      reader.readMessage(value,proto.envoy.api.v2.endpoint.Endpoint.deserializeBinaryFromReader);
      msg.setEndpoint(value);
      break;
    case 2:
      var value = /** @type {!proto.envoy.api.v2.core.HealthStatus} */ (reader.readEnum());
      msg.setHealthStatus(value);
      break;
    case 3:
      var value = new envoy_api_v2_core_base_pb.Metadata;
      reader.readMessage(value,envoy_api_v2_core_base_pb.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.UInt32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt32Value.deserializeBinaryFromReader);
      msg.setLoadBalancingWeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.endpoint.LbEndpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.endpoint.LbEndpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.endpoint.LbEndpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEndpoint();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.envoy.api.v2.endpoint.Endpoint.serializeBinaryToWriter
    );
  }
  f = message.getHealthStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      envoy_api_v2_core_base_pb.Metadata.serializeBinaryToWriter
    );
  }
  f = message.getLoadBalancingWeight();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.UInt32Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional Endpoint endpoint = 1;
 * @return {?proto.envoy.api.v2.endpoint.Endpoint}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.getEndpoint = function() {
  return /** @type{?proto.envoy.api.v2.endpoint.Endpoint} */ (
    jspb.Message.getWrapperField(this, proto.envoy.api.v2.endpoint.Endpoint, 1));
};


/** @param {?proto.envoy.api.v2.endpoint.Endpoint|undefined} value */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.setEndpoint = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.envoy.api.v2.endpoint.LbEndpoint.prototype.clearEndpoint = function() {
  this.setEndpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.hasEndpoint = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional envoy.api.v2.core.HealthStatus health_status = 2;
 * @return {!proto.envoy.api.v2.core.HealthStatus}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.getHealthStatus = function() {
  return /** @type {!proto.envoy.api.v2.core.HealthStatus} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.envoy.api.v2.core.HealthStatus} value */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.setHealthStatus = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional envoy.api.v2.core.Metadata metadata = 3;
 * @return {?proto.envoy.api.v2.core.Metadata}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.getMetadata = function() {
  return /** @type{?proto.envoy.api.v2.core.Metadata} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_base_pb.Metadata, 3));
};


/** @param {?proto.envoy.api.v2.core.Metadata|undefined} value */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.envoy.api.v2.endpoint.LbEndpoint.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.UInt32Value load_balancing_weight = 4;
 * @return {?proto.google.protobuf.UInt32Value}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.getLoadBalancingWeight = function() {
  return /** @type{?proto.google.protobuf.UInt32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt32Value, 4));
};


/** @param {?proto.google.protobuf.UInt32Value|undefined} value */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.setLoadBalancingWeight = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.envoy.api.v2.endpoint.LbEndpoint.prototype.clearLoadBalancingWeight = function() {
  this.setLoadBalancingWeight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.api.v2.endpoint.LbEndpoint.prototype.hasLoadBalancingWeight = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.api.v2.endpoint.LocalityLbEndpoints.repeatedFields_, null);
};
goog.inherits(proto.envoy.api.v2.endpoint.LocalityLbEndpoints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.api.v2.endpoint.LocalityLbEndpoints.displayName = 'proto.envoy.api.v2.endpoint.LocalityLbEndpoints';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.endpoint.LocalityLbEndpoints.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.endpoint.LocalityLbEndpoints} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.toObject = function(includeInstance, msg) {
  var f, obj = {
    locality: (f = msg.getLocality()) && envoy_api_v2_core_base_pb.Locality.toObject(includeInstance, f),
    lbEndpointsList: jspb.Message.toObjectList(msg.getLbEndpointsList(),
    proto.envoy.api.v2.endpoint.LbEndpoint.toObject, includeInstance),
    loadBalancingWeight: (f = msg.getLoadBalancingWeight()) && google_protobuf_wrappers_pb.UInt32Value.toObject(includeInstance, f),
    priority: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.endpoint.LocalityLbEndpoints}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.endpoint.LocalityLbEndpoints;
  return proto.envoy.api.v2.endpoint.LocalityLbEndpoints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.endpoint.LocalityLbEndpoints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.endpoint.LocalityLbEndpoints}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_api_v2_core_base_pb.Locality;
      reader.readMessage(value,envoy_api_v2_core_base_pb.Locality.deserializeBinaryFromReader);
      msg.setLocality(value);
      break;
    case 2:
      var value = new proto.envoy.api.v2.endpoint.LbEndpoint;
      reader.readMessage(value,proto.envoy.api.v2.endpoint.LbEndpoint.deserializeBinaryFromReader);
      msg.addLbEndpoints(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.UInt32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt32Value.deserializeBinaryFromReader);
      msg.setLoadBalancingWeight(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPriority(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.endpoint.LocalityLbEndpoints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.endpoint.LocalityLbEndpoints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocality();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_api_v2_core_base_pb.Locality.serializeBinaryToWriter
    );
  }
  f = message.getLbEndpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.envoy.api.v2.endpoint.LbEndpoint.serializeBinaryToWriter
    );
  }
  f = message.getLoadBalancingWeight();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.UInt32Value.serializeBinaryToWriter
    );
  }
  f = message.getPriority();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
};


/**
 * optional envoy.api.v2.core.Locality locality = 1;
 * @return {?proto.envoy.api.v2.core.Locality}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.getLocality = function() {
  return /** @type{?proto.envoy.api.v2.core.Locality} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_base_pb.Locality, 1));
};


/** @param {?proto.envoy.api.v2.core.Locality|undefined} value */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.setLocality = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.clearLocality = function() {
  this.setLocality(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.hasLocality = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated LbEndpoint lb_endpoints = 2;
 * @return {!Array.<!proto.envoy.api.v2.endpoint.LbEndpoint>}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.getLbEndpointsList = function() {
  return /** @type{!Array.<!proto.envoy.api.v2.endpoint.LbEndpoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.api.v2.endpoint.LbEndpoint, 2));
};


/** @param {!Array.<!proto.envoy.api.v2.endpoint.LbEndpoint>} value */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.setLbEndpointsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.envoy.api.v2.endpoint.LbEndpoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.api.v2.endpoint.LbEndpoint}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.addLbEndpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.envoy.api.v2.endpoint.LbEndpoint, opt_index);
};


proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.clearLbEndpointsList = function() {
  this.setLbEndpointsList([]);
};


/**
 * optional google.protobuf.UInt32Value load_balancing_weight = 3;
 * @return {?proto.google.protobuf.UInt32Value}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.getLoadBalancingWeight = function() {
  return /** @type{?proto.google.protobuf.UInt32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt32Value, 3));
};


/** @param {?proto.google.protobuf.UInt32Value|undefined} value */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.setLoadBalancingWeight = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.clearLoadBalancingWeight = function() {
  this.setLoadBalancingWeight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.hasLoadBalancingWeight = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional uint32 priority = 5;
 * @return {number}
 */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.getPriority = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.envoy.api.v2.endpoint.LocalityLbEndpoints.prototype.setPriority = function(value) {
  jspb.Message.setField(this, 5, value);
};


goog.object.extend(exports, proto.envoy.api.v2.endpoint);
