/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.exportSymbol('proto.envoy.admin.v2alpha.Certificate', null, global);
goog.exportSymbol('proto.envoy.admin.v2alpha.CertificateDetails', null, global);
goog.exportSymbol('proto.envoy.admin.v2alpha.Certificates', null, global);
goog.exportSymbol('proto.envoy.admin.v2alpha.SubjectAlternateName', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.admin.v2alpha.Certificates = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.admin.v2alpha.Certificates.repeatedFields_, null);
};
goog.inherits(proto.envoy.admin.v2alpha.Certificates, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.admin.v2alpha.Certificates.displayName = 'proto.envoy.admin.v2alpha.Certificates';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.admin.v2alpha.Certificates.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.admin.v2alpha.Certificates.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.admin.v2alpha.Certificates.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.admin.v2alpha.Certificates} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.admin.v2alpha.Certificates.toObject = function(includeInstance, msg) {
  var f, obj = {
    certificatesList: jspb.Message.toObjectList(msg.getCertificatesList(),
    proto.envoy.admin.v2alpha.Certificate.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.admin.v2alpha.Certificates}
 */
proto.envoy.admin.v2alpha.Certificates.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.admin.v2alpha.Certificates;
  return proto.envoy.admin.v2alpha.Certificates.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.admin.v2alpha.Certificates} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.admin.v2alpha.Certificates}
 */
proto.envoy.admin.v2alpha.Certificates.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.admin.v2alpha.Certificate;
      reader.readMessage(value,proto.envoy.admin.v2alpha.Certificate.deserializeBinaryFromReader);
      msg.addCertificates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.admin.v2alpha.Certificates.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.admin.v2alpha.Certificates.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.admin.v2alpha.Certificates} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.admin.v2alpha.Certificates.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCertificatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.envoy.admin.v2alpha.Certificate.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Certificate certificates = 1;
 * @return {!Array.<!proto.envoy.admin.v2alpha.Certificate>}
 */
proto.envoy.admin.v2alpha.Certificates.prototype.getCertificatesList = function() {
  return /** @type{!Array.<!proto.envoy.admin.v2alpha.Certificate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.admin.v2alpha.Certificate, 1));
};


/** @param {!Array.<!proto.envoy.admin.v2alpha.Certificate>} value */
proto.envoy.admin.v2alpha.Certificates.prototype.setCertificatesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.envoy.admin.v2alpha.Certificate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.admin.v2alpha.Certificate}
 */
proto.envoy.admin.v2alpha.Certificates.prototype.addCertificates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.envoy.admin.v2alpha.Certificate, opt_index);
};


proto.envoy.admin.v2alpha.Certificates.prototype.clearCertificatesList = function() {
  this.setCertificatesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.admin.v2alpha.Certificate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.admin.v2alpha.Certificate.repeatedFields_, null);
};
goog.inherits(proto.envoy.admin.v2alpha.Certificate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.admin.v2alpha.Certificate.displayName = 'proto.envoy.admin.v2alpha.Certificate';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.admin.v2alpha.Certificate.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.admin.v2alpha.Certificate.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.admin.v2alpha.Certificate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.admin.v2alpha.Certificate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.admin.v2alpha.Certificate.toObject = function(includeInstance, msg) {
  var f, obj = {
    caCertList: jspb.Message.toObjectList(msg.getCaCertList(),
    proto.envoy.admin.v2alpha.CertificateDetails.toObject, includeInstance),
    certChainList: jspb.Message.toObjectList(msg.getCertChainList(),
    proto.envoy.admin.v2alpha.CertificateDetails.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.admin.v2alpha.Certificate}
 */
proto.envoy.admin.v2alpha.Certificate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.admin.v2alpha.Certificate;
  return proto.envoy.admin.v2alpha.Certificate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.admin.v2alpha.Certificate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.admin.v2alpha.Certificate}
 */
proto.envoy.admin.v2alpha.Certificate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.admin.v2alpha.CertificateDetails;
      reader.readMessage(value,proto.envoy.admin.v2alpha.CertificateDetails.deserializeBinaryFromReader);
      msg.addCaCert(value);
      break;
    case 2:
      var value = new proto.envoy.admin.v2alpha.CertificateDetails;
      reader.readMessage(value,proto.envoy.admin.v2alpha.CertificateDetails.deserializeBinaryFromReader);
      msg.addCertChain(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.admin.v2alpha.Certificate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.admin.v2alpha.Certificate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.admin.v2alpha.Certificate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.admin.v2alpha.Certificate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCaCertList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.envoy.admin.v2alpha.CertificateDetails.serializeBinaryToWriter
    );
  }
  f = message.getCertChainList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.envoy.admin.v2alpha.CertificateDetails.serializeBinaryToWriter
    );
  }
};


/**
 * repeated CertificateDetails ca_cert = 1;
 * @return {!Array.<!proto.envoy.admin.v2alpha.CertificateDetails>}
 */
proto.envoy.admin.v2alpha.Certificate.prototype.getCaCertList = function() {
  return /** @type{!Array.<!proto.envoy.admin.v2alpha.CertificateDetails>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.admin.v2alpha.CertificateDetails, 1));
};


/** @param {!Array.<!proto.envoy.admin.v2alpha.CertificateDetails>} value */
proto.envoy.admin.v2alpha.Certificate.prototype.setCaCertList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.envoy.admin.v2alpha.CertificateDetails=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.admin.v2alpha.CertificateDetails}
 */
proto.envoy.admin.v2alpha.Certificate.prototype.addCaCert = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.envoy.admin.v2alpha.CertificateDetails, opt_index);
};


proto.envoy.admin.v2alpha.Certificate.prototype.clearCaCertList = function() {
  this.setCaCertList([]);
};


/**
 * repeated CertificateDetails cert_chain = 2;
 * @return {!Array.<!proto.envoy.admin.v2alpha.CertificateDetails>}
 */
proto.envoy.admin.v2alpha.Certificate.prototype.getCertChainList = function() {
  return /** @type{!Array.<!proto.envoy.admin.v2alpha.CertificateDetails>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.admin.v2alpha.CertificateDetails, 2));
};


/** @param {!Array.<!proto.envoy.admin.v2alpha.CertificateDetails>} value */
proto.envoy.admin.v2alpha.Certificate.prototype.setCertChainList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.envoy.admin.v2alpha.CertificateDetails=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.admin.v2alpha.CertificateDetails}
 */
proto.envoy.admin.v2alpha.Certificate.prototype.addCertChain = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.envoy.admin.v2alpha.CertificateDetails, opt_index);
};


proto.envoy.admin.v2alpha.Certificate.prototype.clearCertChainList = function() {
  this.setCertChainList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.admin.v2alpha.CertificateDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.admin.v2alpha.CertificateDetails.repeatedFields_, null);
};
goog.inherits(proto.envoy.admin.v2alpha.CertificateDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.admin.v2alpha.CertificateDetails.displayName = 'proto.envoy.admin.v2alpha.CertificateDetails';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.admin.v2alpha.CertificateDetails.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.admin.v2alpha.CertificateDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.admin.v2alpha.CertificateDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.admin.v2alpha.CertificateDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 1, ""),
    serialNumber: jspb.Message.getFieldWithDefault(msg, 2, ""),
    subjectAltNamesList: jspb.Message.toObjectList(msg.getSubjectAltNamesList(),
    proto.envoy.admin.v2alpha.SubjectAlternateName.toObject, includeInstance),
    daysUntilExpiration: jspb.Message.getFieldWithDefault(msg, 4, 0),
    validFrom: (f = msg.getValidFrom()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    expirationTime: (f = msg.getExpirationTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.admin.v2alpha.CertificateDetails}
 */
proto.envoy.admin.v2alpha.CertificateDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.admin.v2alpha.CertificateDetails;
  return proto.envoy.admin.v2alpha.CertificateDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.admin.v2alpha.CertificateDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.admin.v2alpha.CertificateDetails}
 */
proto.envoy.admin.v2alpha.CertificateDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSerialNumber(value);
      break;
    case 3:
      var value = new proto.envoy.admin.v2alpha.SubjectAlternateName;
      reader.readMessage(value,proto.envoy.admin.v2alpha.SubjectAlternateName.deserializeBinaryFromReader);
      msg.addSubjectAltNames(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setDaysUntilExpiration(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setValidFrom(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpirationTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.admin.v2alpha.CertificateDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.admin.v2alpha.CertificateDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.admin.v2alpha.CertificateDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSerialNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSubjectAltNamesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.envoy.admin.v2alpha.SubjectAlternateName.serializeBinaryToWriter
    );
  }
  f = message.getDaysUntilExpiration();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getValidFrom();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getExpirationTime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string path = 1;
 * @return {string}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.setPath = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string serial_number = 2;
 * @return {string}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.getSerialNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.setSerialNumber = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * repeated SubjectAlternateName subject_alt_names = 3;
 * @return {!Array.<!proto.envoy.admin.v2alpha.SubjectAlternateName>}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.getSubjectAltNamesList = function() {
  return /** @type{!Array.<!proto.envoy.admin.v2alpha.SubjectAlternateName>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.envoy.admin.v2alpha.SubjectAlternateName, 3));
};


/** @param {!Array.<!proto.envoy.admin.v2alpha.SubjectAlternateName>} value */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.setSubjectAltNamesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.envoy.admin.v2alpha.SubjectAlternateName=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.admin.v2alpha.SubjectAlternateName}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.addSubjectAltNames = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.envoy.admin.v2alpha.SubjectAlternateName, opt_index);
};


proto.envoy.admin.v2alpha.CertificateDetails.prototype.clearSubjectAltNamesList = function() {
  this.setSubjectAltNamesList([]);
};


/**
 * optional uint64 days_until_expiration = 4;
 * @return {number}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.getDaysUntilExpiration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.setDaysUntilExpiration = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp valid_from = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.getValidFrom = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.setValidFrom = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.envoy.admin.v2alpha.CertificateDetails.prototype.clearValidFrom = function() {
  this.setValidFrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.hasValidFrom = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp expiration_time = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.getExpirationTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.setExpirationTime = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.envoy.admin.v2alpha.CertificateDetails.prototype.clearExpirationTime = function() {
  this.setExpirationTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.admin.v2alpha.CertificateDetails.prototype.hasExpirationTime = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.admin.v2alpha.SubjectAlternateName = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.envoy.admin.v2alpha.SubjectAlternateName.oneofGroups_);
};
goog.inherits(proto.envoy.admin.v2alpha.SubjectAlternateName, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.admin.v2alpha.SubjectAlternateName.displayName = 'proto.envoy.admin.v2alpha.SubjectAlternateName';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.NameCase = {
  NAME_NOT_SET: 0,
  DNS: 1,
  URI: 2
};

/**
 * @return {proto.envoy.admin.v2alpha.SubjectAlternateName.NameCase}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.getNameCase = function() {
  return /** @type {proto.envoy.admin.v2alpha.SubjectAlternateName.NameCase} */(jspb.Message.computeOneofCase(this, proto.envoy.admin.v2alpha.SubjectAlternateName.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.admin.v2alpha.SubjectAlternateName.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.admin.v2alpha.SubjectAlternateName} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.toObject = function(includeInstance, msg) {
  var f, obj = {
    dns: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uri: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.admin.v2alpha.SubjectAlternateName}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.admin.v2alpha.SubjectAlternateName;
  return proto.envoy.admin.v2alpha.SubjectAlternateName.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.admin.v2alpha.SubjectAlternateName} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.admin.v2alpha.SubjectAlternateName}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDns(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.admin.v2alpha.SubjectAlternateName.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.admin.v2alpha.SubjectAlternateName} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string dns = 1;
 * @return {string}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.getDns = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.setDns = function(value) {
  jspb.Message.setOneofField(this, 1, proto.envoy.admin.v2alpha.SubjectAlternateName.oneofGroups_[0], value);
};


proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.clearDns = function() {
  jspb.Message.setOneofField(this, 1, proto.envoy.admin.v2alpha.SubjectAlternateName.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.hasDns = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string uri = 2;
 * @return {string}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.setUri = function(value) {
  jspb.Message.setOneofField(this, 2, proto.envoy.admin.v2alpha.SubjectAlternateName.oneofGroups_[0], value);
};


proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.clearUri = function() {
  jspb.Message.setOneofField(this, 2, proto.envoy.admin.v2alpha.SubjectAlternateName.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.admin.v2alpha.SubjectAlternateName.prototype.hasUri = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.envoy.admin.v2alpha);
