/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_api_v2_core_base_pb = require('../../../../envoy/api/v2/core/base_pb.js');
goog.exportSymbol('proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.displayName = 'proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    secretData: (f = msg.getSecretData()) && envoy_api_v2_core_base_pb.DataSource.toObject(includeInstance, f),
    headerKey: jspb.Message.getFieldWithDefault(msg, 2, ""),
    headerPrefix: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig}
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig;
  return proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig}
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_api_v2_core_base_pb.DataSource;
      reader.readMessage(value,envoy_api_v2_core_base_pb.DataSource.deserializeBinaryFromReader);
      msg.setSecretData(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setHeaderKey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setHeaderPrefix(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSecretData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_api_v2_core_base_pb.DataSource.serializeBinaryToWriter
    );
  }
  f = message.getHeaderKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHeaderPrefix();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional envoy.api.v2.core.DataSource secret_data = 1;
 * @return {?proto.envoy.api.v2.core.DataSource}
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.getSecretData = function() {
  return /** @type{?proto.envoy.api.v2.core.DataSource} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_core_base_pb.DataSource, 1));
};


/** @param {?proto.envoy.api.v2.core.DataSource|undefined} value */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.setSecretData = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.clearSecretData = function() {
  this.setSecretData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.hasSecretData = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string header_key = 2;
 * @return {string}
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.getHeaderKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.setHeaderKey = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string header_prefix = 3;
 * @return {string}
 */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.getHeaderPrefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.envoy.config.grpc_credential.v2alpha.FileBasedMetadataConfig.prototype.setHeaderPrefix = function(value) {
  jspb.Message.setField(this, 3, value);
};


goog.object.extend(exports, proto.envoy.config.grpc_credential.v2alpha);
